In [474]:
#import necessary libraries
import json #will need to transform imbedded JSON columns
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')
pd.options.display.max_columns = 999
pd.options.display.max_rows = 5000
%matplotlib inline

## Read in Kaggle Data

In [475]:
#read in movie dataset 
movie = pd.read_csv('tmdb_5000_movies.csv')
#read in movie credits dataset
credits = pd.read_csv('tmdb_5000_credits.csv')
#check to see that they have the same amount of records
print(movie.shape)
print(credits.shape)

(4803, 20)
(4803, 4)

In [438]:
df.head(5)

,id,title,genres,keywords,original_language,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,vote_average,vote_count,cast,crew,budget,revenue,year,genres_first3,keywords_first3,production_companies_first3,production_countries_first3,spoken_languages_first3,cast_first3,crew_first3,director,film_country,actor_split,actor_1,actor_2,actor_3,p_comp_split,p_comp_1,p_comp_2,p_comp_3,No_English,highest_paid_actor,Action,Adventure,Fantasy,Crime,Drama,Science Fiction,Animation,Family,Thriller,Western,Comedy,Romance,Horror,Mystery,History,War,Music,Documentary,Foreign,TV Movie,
0,19995,Avatar,"[{'name': 'Action', 'id': 28}, {'name': 'Adven...","[{'name': 'culture clash', 'id': 1463}, {'name...",en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{'name': 'Ingenious Film Partners', 'id': 289...","[{'name': 'United States of America', 'iso_316...",2009-12-10,162.0,"[{'name': 'English', 'iso_639_1': 'en'}, {'nam...",Released,7.2,11800,"[{'name': 'Sam Worthington', 'order': 0, 'id':...","[{'job': 'Editor', 'name': 'Stephen E. Rivkin'...",237000000,2787965087,2009,Action|Adventure|Fantasy,culture clash|future|space war,Ingenious Film Partners|Twentieth Century Fox ...,United States of America|United Kingdom,English|Espa√±ol,Sam Worthington|Zoe Saldana|Sigourney Weaver,Stephen E. Rivkin|Rick Carter|Christopher Boyes,James Cameron,United States of America,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",Sam Worthington,Zoe Saldana,Sigourney Weaver,"[Ingenious Film Partners, Twentieth Century Fo...",Ingenious Film Partners,Twentieth Century Fox Film Corporation,Dune Entertainment,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,285,Pirates of the Caribbean: At World's End,"[{'name': 'Adventure', 'id': 12}, {'name': 'Fa...","[{'name': 'ocean', 'id': 270}, {'name': 'drug ...",en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...","[{'name': 'United States of America', 'iso_316...",2007-05-19,169.0,"[{'name': 'English', 'iso_639_1': 'en'}]",Released,6.9,4500,"[{'name': 'Johnny Depp', 'order': 0, 'id': 85,...","[{'job': 'Director of Photography', 'name': 'D...",300000000,961000000,2007,Adventure|Fantasy|Action,ocean|drug abuse|exotic island,Walt Disney Pictures|Jerry Bruckheimer Films|S...,United States of America,English,Johnny Depp|Orlando Bloom|Keira Knightley,Dariusz Wolski|Gore Verbinski|Jerry Bruckheimer,Gore Verbinski,United States of America,"[Johnny Depp, Orlando Bloom, Keira Knightley]",Johnny Depp,Orlando Bloom,Keira Knightley,"[Walt Disney Pictures, Jerry Bruckheimer Films...",Walt Disney Pictures,Jerry Bruckheimer Films,Second Mate Productions,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,206647,Spectre,"[{'name': 'Action', 'id': 28}, {'name': 'Adven...","[{'name': 'spy', 'id': 470}, {'name': 'based o...",en,A cryptic message from Bond‚Äôs past sends him o...,107.376788,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'name': 'United Kingdom', 'iso_3166_1': 'GB'...",2015-10-26,148.0,"[{'name': 'Fran√ßais', 'iso_639_1': 'fr'}, {'na...",Released,6.3,4466,"[{'name': 'Daniel Craig', 'order': 0, 'id': 87...","[{'job': 'Original Music Composer', 'name': 'T...",245000000,880674609,2015,Action|Adventure|Crime,spy|based on novel|secret agent,Columbia Pictures|Danjaq|B24,United Kingdom|United States of America,Fran√ßais|English|Espa√±ol,Daniel Craig|Christoph Waltz|L√©a Seydoux,Thomas Newman|Sam Mendes|Anna Pinnock,Sam Mendes,United Kingdom,"[Daniel Craig, Christoph Waltz, L√©a Seydoux]",Daniel Craig,Christoph Waltz,L√©a Seydoux,"[Columbia Pictures, Danjaq, B24]",Columbia Pictures,Danjaq,B24,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,49026,The Dark Knight Rises,"[{'name': 'Action', 'id': 28}, {'name': 'Crime...","[{'name': 'dc comics', 'id': 849}, {'name': 'c...",en,Following the death of District Attorney Harve...,112.312950,"[{'name': 'Legendary Pictures', 'id': 923}, {'...","[{'name': 'United States of America', 'iso_316...",2012-07-16,165.0,"[{'name': 'English', 'iso_639_1': 'en'}]",Released,7.6,9106,"[{'name': 'Christian Bale', 'order': 0, 'id': ...","[{'job': 'Original Music Composer', 'name': 'H...",250000000,1084939099,2012,Action|Crime|Drama,dc comics|crime fighter|terrorist,Legendary Pictures|Warner Bros.|DC Entertainment,United States of America,English,Christian Bale|Michael Caine|Gary Oldman,Hans Zimmer|Charles Roven|Christopher Nolan,Christopher Nolan,United States of America,"[Christian Bale, Michael Caine, Gary Oldman]",Christian Bale,Michael Caine,Gary Oldman,"[Legendary Pictures, Warner Bros., DC Entertai...",Legendary Pictures,Warner Bros.,DC Entertainment,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
4,49529,John Carter,"[{'name': 'Action', 'id': 28}, {'name': 'Adven...","[{'name': 'based on novel', 'id': 818}, {'name...",en,"John Carter is a war-weary, former military ca...",43.926995,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'name': 'United States of America', 'iso_316...",2012-03-07,132.0,"[{'name': 'English', 'iso_639_1': 'en'}]",Released,6.1,2124,"[{'name': 'Taylor Kitsch', 'order': 0, 'id': 6...","[{'job': 'Screenplay', 'name': 'Andrew Stanton...",260000000,284139100,2012,Action|Adventure|Science Fiction,based on novel|mars|medallion,Walt Disney Pictures,United States of America,English,Taylor Kitsch|Lynn Collins|Samantha Morton,Andrew Stanton|Andrew Stanton|John Lasseter,Andrew Stanton,United States of America,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",Taylor Kitsch,Lynn Collins,Samantha Morton,[Walt Disney Pictures],Walt Disney Pictures,Walt Disney Pictures,Walt Disney Pictures,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [476]:
#merge datasets using unique ID 'movie_id'; ensure 'one-to-one' relationship
df = movie.merge(credits,left_on='id', right_on='movie_id', how='inner', suffixes=('','_y'),validate='one_to_one')
#need to drop any overlapping column names that end in suffix _y
to_drop = [x for x in df if x.endswith('_y')|x.endswith('_id')|x.endswith('_title')]
df.drop(to_drop, axis=1, inplace=True)
#re-arrange order to my liking 
column_order = ['id', 'title','genres', 'homepage', 'keywords', 'original_language',
        'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'runtime',
       'spoken_languages', 'status', 'tagline', 'vote_average',
       'vote_count', 'cast', 'crew', 'budget','revenue']

df = df.reindex(columns=column_order)

In [440]:
#let's check my assumptions of the data set e.g. data types, missing values etc...
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 21 columns):
id                      4803 non-null int64
title                   4803 non-null object
genres                  4803 non-null object
homepage                1712 non-null object
keywords                4803 non-null object
original_language       4803 non-null object
overview                4800 non-null object
popularity              4803 non-null float64
production_companies    4803 non-null object
production_countries    4803 non-null object
release_date            4802 non-null object
runtime                 4801 non-null float64
spoken_languages        4803 non-null object
status                  4803 non-null object
tagline                 3959 non-null object
vote_average            4803 non-null float64
vote_count              4803 non-null int64
cast                    4803 non-null object
crew                    4803 non-null object
budget                  4803 non-null int64
revenue                 4803 non-null int64
dtypes: float64(3), int64(4), object(14)
memory usage: 825.5+ KB

it appears there are some columns that have quite a bit of missing data e.g. homepage, tagline etc...Let's take a look at the top 5

In [441]:
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(5)

              Total   Percent
homepage       3091  0.643556
tagline         844  0.175724
overview          3  0.000625
runtime           2  0.000416
release_date      1  0.000208

wow...over 64% and 17% is missing in the 'homepage' and 'tagline' columns
since I know I'm going to use those in any part of my analysis, let's remove

In [478]:
df.drop(['homepage','tagline'], axis=1, inplace=True)
#just because I'm lazy and there aren't many, I'm going to get rid of records where are missing values for some of the columns
df = df.dropna(how='any',axis=0)

In [477]:
#since I know I going to want to use the qualities of the date date type, let's change to correct format
df['release_date'] = pd.to_datetime(df['release_date'])
df['year'] = df['release_date'].dt.year

## Transforming JSON columns

In [479]:
#let's use a some for loops to identify all the JSON files that need to flattened into subsequent columns
json_cols = []
for c, i in df.iteritems():
    if type(df[c].loc[0]) == str:
        if "[{" in (df.loc[0,c]):
            json_cols.append(c)

#let's create a function to split those columns using '|' delimiter            
def pipe_flatten_names(col):
    return '|'.join(x['name'] for x in col[:3])

#let's use the 'json.loads' method + flatten name function, taking only the first 3 values
for col in json_cols:
    df[col] = df[col].apply(json.loads)
    df[col+"_first3"] = df[col].apply(pipe_flatten_names)

## Further Feature Creation

In [480]:
#let's create a function to get the director from crew column
def grab_director(crew_col):
    directors = [x['name'] for x in crew_col if x['job'] == 'Director']
    if len(directors) > 0:
        return directors[0]
    else:
        return np.nan

#apply grab_director function
df['director'] = df.crew.apply(grab_director)

#split the production companies, taking the first value
df['film_country'] = df.production_countries_first3.str.split('|')
df['film_country'] = [x[0] for x in df['film_country']]

#split the cast column, take the first 3 values
df['actor_split'] = df.cast_first3.str.split('|')
df['actor_1'] = [x[0] for x in df['actor_split']]
df['actor_2'] = [x[1] if len(x)>=2 else x[0] for x in df['actor_split']]
df['actor_3'] = [x[2] if len(x)>=3 else x[0] for x in df['actor_split']]

#split the cast column, take the first 3 values
df['p_comp_split'] = df.production_companies_first3.str.split('|')
df['p_comp_1'] = [x[0] for x in df['p_comp_split']]
df['p_comp_2'] = [x[1] if len(x)>=2 else x[0] for x in df['p_comp_split']]
df['p_comp_3'] = [x[2] if len(x)>=3 else x[0] for x in df['p_comp_split']]

#create a binary label for to mark whether a film is spoken at all in english i.e. 0 or is exclusively non-english = 1
df['No_English'] = [0 if 'English' in ele else 1 for ele in df['spoken_languages_first3']]

## Add a variable for the highest paid actors

I'm interested to see how (if at all) actors/actresses who are in the list of highest paid film actors impacts a title's revenue at the box office. To do this, I will take a list of the highest paid from Wikipedia https://en.wikipedia.org/wiki/List_of_highest_paid_film_actors and create a binary variable.

In [481]:
highest_paid_actors = [
    'Keanu Reeves',
'Bruce Willis',
'Tom Cruise',
'Will Smith',
'Robert Downey Jr.',
'Sandra Bullock',
'Tom Hanks',
'Tom Cruise',
'Harrison Ford',
'Jack Nicholson',
'Leonardo DiCaprio',
'Robert Downey Jr.',
'Johnny Depp',
'Robert Downey Jr.',
'Cameron Diaz',
'Leonardo DiCaprio',
'Tom Hanks',
'Johnny Depp',
'Aamir Khan',
'Jim Carrey',
'Arnold Schwarzenegger',
'Mel Gibson',
'Brad Pitt']

df['highest_paid_actor'] = 0
for column in actor_cols:
    df.loc[df[column].isin(highest_paid_actors), 'highest_paid_actor'] = 1

## Add a variable for directors who have been nominated for "best director" academy award

Similary, I'm interested to see how (if at all) directors who were nominated for an academy award impacts revenue at the box office. To do this, I will take a list of nominated directors https://en.wikipedia.org/wiki/Academy_Award_for_Best_Director and create an associated binary variable.

In [483]:
nomin_dir = ['Lionel Barrymore',
'Harry Beaumont',
'Irving Cummings',
'Frank Lloyd',
'Weary River',
'Ernst Lubitsch',
'Clarence Brown',
'Romance',
'Robert Z. Leonard',
'Ernst Lubitsch',
'King Vidor',
'Clarence Brown',
'Lewis Milestone',
'Wesley Ruggles',
'Josef von Sternberg',
'King Vidor',
'Josef von Sternberg',
'Frank Capra',
'George Cukor',
'Victor Schertzinger',
'W. S. Van Dyke',
'Henry Hathaway',
'Frank Lloyd',
'Gregory La Cava',
'Robert Z. Leonard',
'W. S. Van Dyke',
'William Wyler',
'William Dieterle',
'Sidney Franklin',
'Gregory La Cava',
'William A. Wellman',
'Michael Curtiz',
'Four Daughters',
'Norman Taurog',
'King Vidor',
'Frank Capra',
'John Ford',
'Sam Wood',
'William Wyler',
'George Cukor',
'Alfred Hitchcock',
'Sam Wood',
'William Wyler',
'Alexander Hall',
'Howard Hawks',
'Orson Welles',
'William Wyler',
'Michael Curtiz',
'John Farrow',
'Mervyn LeRoy',
'Sam Wood',
'Clarence Brown',
'Henry King',
'Ernst Lubitsch',
'George Stevens',
'Alfred Hitchcock',
'Henry King',
'Otto Preminger',
'Billy Wilder',
'Clarence Brown',
'Alfred Hitchcock',
'Leo McCarey',
'Jean Renoir',
'Clarence Brown',
'Frank Capra',
'David Lean',
'Robert Siodmak',
'George Cukor',
'Edward Dmytryk',
'Henry Koster',
'David Lean',
'Anatole Litvak',
'Jean Negulesco',
'Laurence Olivier',
'Fred Zinnemann',
'Carol Reed',
'Robert Rossen',
'William A. Wellman',
'William Wyler',
'George Cukor',
'John Huston',
'Carol Reed',
'Billy Wilder',
'John Huston',
'Elia Kazan',
'Vincente Minnelli',
'William Wyler',
'Cecil B. DeMille',
'John Huston',
'Joseph L. Mankiewicz',
'Fred Zinnemann',
'George Stevens',
'Charles Walters',
'Billy Wilder',
'William Wyler',
'Alfred Hitchcock',
'George Seaton',
'William A. Wellman',
'Billy Wilder',
'Elia Kazan',
'David Lean',
'Joshua Logan',
'John Sturges',
'Michael Anderson',
'Walter Lang',
'King Vidor',
'William Wyler',
'Joshua Logan',
'Sidney Lumet',
'Mark Robson',
'Billy Wilder',
'Richard Brooks',
'Stanley Kramer',
'Mark Robson',
'Robert Wise',
'Jack Clayton',
'George Stevens',
'Billy Wilder',
'Fred Zinnemann',
'Jack Cardiff',
'Jules Dassin',
'Alfred Hitchcock',
'Fred Zinnemann',
'Federico Fellini',
'Stanley Kramer',
'Robert Rossen',
'J. Lee Thompson',
'Pietro Germi',
'Robert Mulligan',
'Arthur Penn',
'Frank Perry',
'Federico Fellini',
'Elia Kazan',
'Otto Preminger',
'Martin Ritt',
'Michael Cacoyannis',
'Peter Glenville',
'Stanley Kubrick',
'Robert Stevenson',
'David Lean',
'John Schlesinger',
'Hiroshi Teshigahara',
'William Wyler',
'Michelangelo Antonioni',
'Richard Brooks',
'Claude Lelouch',
'Mike Nichols',
'Richard Brooks',
'Norman Jewison',
'Stanley Kramer',
'Arthur Penn',
'Anthony Harvey',
'Stanley Kubrick',
'Gillo Pontecorvo',
'Franco Zeffirelli',
'Costa-Gavras',
'George Roy Hill',
'Arthur Penn',
'Sydney Pollack',
'Robert Altman',
'Federico Fellini',
'Arthur Hiller',
'Ken Russell',
'Peter Bogdanovich',
'Norman Jewison',
'Stanley Kubrick',
'John Schlesinger',
'John Boorman',
'Francis Ford Coppola',
'Joseph L. Mankiewicz',
'Jan Troell',
'Ingmar Bergman',
'Bernardo Bertolucci',
'William Friedkin',
'George Lucas',
'John Cassavetes',
'Bob Fosse',
'Roman Polanski',
'Fran√ßois Truffaut',
'Robert Altman',
'Federico Fellini',
'Stanley Kubrick',
'Sidney Lumet',
'Ingmar Bergman',
'Sidney Lumet',
'Alan J. Pakula',
'Lina Wertm√ºller',
'George Lucas',
'Herbert Ross',
'Steven Spielberg',
'Fred Zinnemann',
'Woody Allen',
'Hal Ashby',
'Warren Beatty¬†&¬†Buck Henry',
'Alan Parker',
'Francis Ford Coppola',
'Bob Fosse',
'√âdouard Molinaro',
'Peter Yates',
'David Lynch',
'Roman Polanski',
'Richard Rush',
'Martin Scorsese',
'Hugh Hudson',
'Louis Malle',
'Mark Rydell',
'Steven Spielberg',
'Sidney Lumet',
'Wolfgang Petersen',
'Sydney Pollack',
'Steven Spielberg',
'Bruce Beresford',
'Ingmar Bergman',
'Mike Nichols',
'Peter Yates',
'Woody Allen',
'Robert Benton',
'Roland Joff√©',
'David Lean',
'H√©ctor Babenco',
'John Huston',
'Akira Kurosawa',
'Peter Weir',
'Woody Allen',
'James Ivory',
'Roland Joff√©',
'David Lynch',
'John Boorman',
'Lasse Hallstr√∂m',
'Norman Jewison',
'Adrian Lyne',
'Charles Crichton',
'Mike Nichols',
'Alan Parker',
'Martin Scorsese',
'Woody Allen',
'Kenneth Branagh',
'Jim Sheridan',
'Peter Weir',
'Francis Ford Coppola',
'Stephen Frears',
'Barbet Schroeder',
'Martin Scorsese',
'Barry Levinson',
'Ridley Scott',
'John Singleton',
'Oliver Stone',
'Robert Altman',
'Martin Brest',
'James Ivory',
'Neil Jordan',
'Robert Altman',
'Jane Campion',
'James Ivory',
'Jim Sheridan',
'Woody Allen',
'Krzysztof Kie≈õlowski',
'Robert Redford',
'Quentin Tarantino',
'Mike Figgis',
'Chris Noonan',
'Michael Radford',
'Tim Robbins',
'Joel Coen',
'Milo≈° Forman',
'Scott Hicks',
'Mike Leigh',
'Peter Cattaneo',
'Atom Egoyan',
'Curtis Hanson',
'Gus Van Sant',
'Roberto Benigni',
'John Madden',
'Terrence Malick',
'Peter Weir',
'Lasse Hallstr√∂m',
'Spike Jonze',
'Michael Mann',
'M. Night Shyamalan',
'Stephen Daldry',
'Ang Lee',
'Ridley Scott',
'Steven Soderbergh',
'Robert Altman',
'Peter Jackson',
'David Lynch',
'Ridley Scott',
'Pedro Almod√≥var',
'Stephen Daldry',
'Rob Marshall',
'Martin Scorsese',
'Sofia Coppola',
'Clint Eastwood',
'Fernando Meirelles',
'Peter Weir',
'Taylor Hackford',
'Mike Leigh',
'Alexander Payne',
'Martin Scorsese',
'George Clooney',
'Paul Haggis',
'Bennett Miller',
'Steven Spielberg',
'Clint Eastwood',
'Stephen Frears',
'Paul Greengrass',
'Alejandro G. I√±√°rritu',
'Paul Thomas Anderson',
'Tony Gilroy',
'Jason Reitman',
'Julian Schnabel',
'Stephen Daldry',
'David Fincher',
'Ron Howard',
'Gus Van Sant',
'Lee Daniels',
'Jason Reitman',
'Quentin Tarantino',
'Darren Aronofsky',
'Coen Brothers',
'David Fincher',
'David O. Russell',
'Woody Allen',
'Terrence Malick',
'Alexander Payne',
'Martin Scorsese',
'Michael Haneke',
'David O. Russell',
'Steven Spielberg',
'Benh Zeitlin',
'Steve McQueen',
'Alexander Payne',
'David O. Russell',
'Martin Scorsese',
'Wes Anderson',
'Richard Linklater',
'Bennett Miller',
'Morten Tyldum',
'Lenny Abrahamson',
'Tom McCarthy',
'Adam McKay',
'George Miller',
'Mel Gibson',
'Barry Jenkins',
'Kenneth Lonergan',
'Denis Villeneuve',
'Paul Thomas Anderson',
'Greta Gerwig',
'Christopher Nolan',
'Jordan Peele',
'Yorgos Lanthimos',
'Spike Lee',
'Adam McKay',
'Pawe≈Ç Pawlikowski']


df['nom_dir'] = [1 if x in nomin_dir else 0 for x in df.director]

## Create dummy variables for 'Genres_first3'

In [485]:
def get_genre_occurence(columnName):
    genre_Occur = []
    for i in df['genres_first3']:
        split_genre = list(map(str, i.split('|')))
        for j in split_genre:
            if j not in genre_Occur:
                genre_Occur.append(j)
    return genre_Occur

genre = []
genre = get_genre_occurence("genres")
for word in genre:
    df[word] = df['genres'].map(lambda s: 1 if word in str(s) else 0)
#let's see if it worked
df.loc[:,'No_English': 'Foreign'].head(5)

,No_English,highest_paid_actor,nomin_director,nom_dir,Action,Adventure,Fantasy,Crime,Drama,Science Fiction,Animation,Family,Thriller,Western,Comedy,Romance,Horror,Mystery,History,War,Music,Documentary,Foreign
0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [487]:
keep = ['popularity','runtime', 'vote_average',
       'vote_count','budget', 'revenue', 
       'No_English', 'highest_paid_actor', 'nom_dir', 'Action', 'Adventure',
       'Fantasy', 'Crime', 'Drama', 'Science Fiction', 'Animation', 'Family',
       'Thriller', 'Western', 'Comedy', 'Romance', 'Horror', 'Mystery',
       'History', 'War', 'Music', 'Documentary', 'Foreign', 'TV Movie']
df_model = df[keep]
df_model.to_csv('for_model.csv')